version: 2
updates:
  - package-ecosystem: "gradle"
    directory: "/"
    schedule:
      interval: "weekly"
    labels: [ "version update" ]
    groups:
      kotlin-ksp:
        patterns:
          - "org.jetbrains.kotlin:*"
          - "org.jetbrains.kotlin.jvm"
          - "com.google.devtools.ksp"
    open-pull-requests-limit: 10