name: Build debug apk

on:
  pull_request:
    branches:
      - develop
    paths-ignore:
      - '.github/**'
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build_debug_apk:
    name: Build debug apk
    runs-on: ubuntu-latest
    environment: development
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Decode google-services.json
        env:
          DEBUG_GOOGLE_SERVICES_JSON: ${{ secrets.DEBUG_GOOGLE_SERVICES_JSON }}
        run: |
            echo $DEBUG_GOOGLE_SERVICES_JSON | base64 --decode > ./app/google-services.json

      - name: Assemble the project
        run: ./gradlew assembleDebug

      - name: Obtain debug apk
        if: always()
        run: cp $(find . -regex '.*outputs/apk/.*debug.apk') pr-debug.apk

      - name: Upload debug apk
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: pr-debug
          path: pr-debug.apk